name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run Sail up
        run: ./vendor/bin/sail up

      - name: Run Sail migrate
        run: ./vendor/bin/sail artisan migrate --seed

      - name: Run tests
        run: ./vendor/bin/sail artisan test
